"""Central configuration for the graph intelligence engine."""

from pathlib import Path

DATA_DIR = Path("data")
OUTPUT_DIR = Path("output")

NODES_FILE = "nodes.parquet"
EDGES_FILE = "edges.parquet"
TRANSACTIONS_FILE = "transactions.parquet"

EXPECTED_NODE_COUNT = 2248
EXPECTED_EDGE_COUNT = 3119
EXPECTED_TRANSACTION_COUNT = 4840
EXPECTED_SEED_COUNT = 81
EXPECTED_ISOLATED_COUNT = 19
EXPECTED_EDGE_COMPONENT_COUNT = 16
EXPECTED_TOTAL_COMPONENT_COUNT = 35
EXPECTED_BOUNDARY_NODE_COUNT = 444
EXPECTED_UNOBSERVED_INFLOW_COUNT = 42
EXPECTED_LARGEST_EDGE_COMPONENT_SIZE = 1877
EXPECTED_SECOND_LARGEST_EDGE_COMPONENT_SIZE = 270

BOUNDARY_DEPTH = 4
MIN_TRANSACTION_KZT = 5000
EXTERNAL_FUNDING_THRESHOLD_KZT = 1000000
EDGE_SUM_REL_TOLERANCE = 1e-12
EDGE_SUM_ABS_TOLERANCE_KZT = 0.01

EXPECTED_START_DATE = "2026-07-01"
EXPECTED_END_DATE = "2026-07-31"

ZERO = 0
ZERO_FLOAT = 0.0
ONE = 1
ONE_FLOAT = 1.0
ROLE_SCORE_PLACEHOLDER = ZERO_FLOAT
ROLE_PLACEHOLDER = ""
CLUSTER_ID_PLACEHOLDER = -ONE
PRIORITY_SCORE_PLACEHOLDER = ZERO_FLOAT

JSON_INDENT = 2
JSON_ENCODING = "utf-8"
CSV_ENCODING = "utf-8"
CSV_LINE_TERMINATOR = "\n"

NODE_COLUMNS = ("gid", "depth", "is_seed")
EDGE_COLUMNS = ("src", "dst", "sum_kzt", "n_tx", "depth")
TRANSACTION_COLUMNS = ("src", "dst", "date", "sum_kzt")

REQUIRED_ROLE_COLUMNS = (
    "gid",
    "role",
    "role_score",
    "cluster_id",
    "priority_score",
    "evidence",
)
FOUNDATION_METRIC_COLUMNS = (
    "depth",
    "is_seed",
    "in_deg",
    "out_deg",
    "in_kzt",
    "out_kzt",
    "in_tx",
    "out_tx",
    "pass_through",
    "retention",
    "ext_inflow",
    "seed_payers",
    "seed_reach2",
    "pagerank",
    "betweenness",
    "component_id",
    "component_size",
    "truncated_by_depth",
)
NODE_ROLE_COLUMNS = REQUIRED_ROLE_COLUMNS + FOUNDATION_METRIC_COLUMNS
CLUSTER_EXPORT_COLUMNS = (
    "cluster_id",
    "n_nodes",
    "n_seed",
    "sum_kzt_internal",
    "top_gids",
    "hypothesis",
)
TOP_NODE_EXPORT_COLUMNS = (
    "rank",
    "gid",
    "role",
    "priority_score",
    "why",
)

ROLE_SCORE_MIN = 0.5
ROLE_SCORE_MAX = 1.0
EVIDENCE_MAX_CHARACTERS = 200
TOP_NODE_COUNT = 30
TOP_NODE_MINIMUM_COUNT = 20
LOUVAIN_SEED = 42
FAST_TRANSFER_WINDOW_DAYS = 2
SEED_REACH_DISTANCE = 2
CONSOLIDATOR_AMOUNT_PERCENTILE = 0.95
ROLE_SCORE_COORDINATOR_NORMALIZER = 3.0
ROLE_SCORE_DISTRIBUTOR_NORMALIZER = 60
ROLE_SCORE_CONSOLIDATOR_IN_DEGREE_NORMALIZER = 15
ROLE_SCORE_CONSOLIDATOR_SEED_REACH_NORMALIZER = 5
ROLE_SCORE_TRANSIT_DISTANCE_MULTIPLIER = 2.5
ROLE_SCORE_FAST_SHARE_MIN = 0.8
ROLE_SCORE_FAST_SHARE_BONUS = 0.1
ROLE_SCORE_TERMINAL_NEAR_BOUNDARY_DEPTH = 2
ROLE_SCORE_TERMINAL_NEAR_BOUNDARY = 0.9
ROLE_SCORE_TERMINAL_FARTHER = 0.7
CLUSTER_SEED_HYPOTHESIS_MIN = 2
CLUSTER_ROLE_MAJORITY_SHARE = 0.5
BASE_SYNC_IN_MAX_NORMALIZER = 5

COORDINATOR_MIN_IN_DEGREE = 5
COORDINATOR_MIN_OUT_DEGREE = 10
DISTRIBUTOR_MIN_OUT_DEGREE = 10
CONSOLIDATOR_MIN_IN_DEGREE = 5
CONSOLIDATOR_ALT_MIN_IN_DEGREE = 3
CONSOLIDATOR_MIN_SEED_REACH = 3
TRANSIT_PASS_THROUGH_MIN = 0.8
TRANSIT_PASS_THROUGH_MAX = 1.2
TERMINAL_MAX_DEPTH = 3

PROPOSED_TERMINAL_RETENTION_MIN = 0.8
PROPOSED_CONSOLIDATOR_IN_KZT_P95 = 613779

BASE_PRIORITY_WEIGHTS = {
    "flow": 0.25,
    "structure": 0.20,
    "volume": 0.15,
    "seed_conv": 0.15,
    "external": 0.15,
    "temporal": 0.10,
}
PROPOSED_PRIORITY_WEIGHTS = {
    "flow": 0.25,
    "structure": 0.20,
    "volume": 0.20,
    "seed_conv": 0.10,
    "external": 0.15,
    "temporal": 0.10,
}
PROPOSED_SYNC_IN_MAX_NORMALIZER = 3
SEED_PRIORITY_MULTIPLIER = 0.8
LOW_PRIORITY_CAP = 0.3
